config/routes.rb
Rails.application.routes.draw do
  
  resources :products
  get 'home/index'

	root 'home#index'
	  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
	resources :users
	resources :products
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
    default_scope -> { order(created_at: :desc) }

end

app/models/user.rb
class User < ApplicationRecord
  has_many :products,dependent: :destroy
  before_save { self.email = email.downcase }
    validates :name,  presence: true, length: { maximum: 50 }

		validates :phone, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX } , 
                    uniqueness: { case_sensitive: false }     

  has_secure_password
  validates :password ,presence: true,length: {minimum: 6}  


  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  def hello
    render html: "hello, world!"
  end


  private

    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:create, :destroy]
    before_action :correct_user, only: :destroy

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
     
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
@product = current_user.products.build(product_params)
    if @product.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      render 'home/index'
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :des, :add, :time)
    end
	   def correct_user
      @product = current_user.product.find_by(id: params[:id])
      redirect_to root_url if @product.nil?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
  	user=User.find_by(email: params[:sessions][:email].downcase)
     if user && user.authenticate(params[:sessions][:password])
        log_in user
        redirect_to user
     else	
      flash.now[:danger] = 'Invalid email/password combination'	
  	  render 'new'
  	 end 
  end
   def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
 
  def new
  	@user=User.new
  end
  def show
  	@user=User.find(params[:id])
  end
  def create
  	@user=User.new(user_params)
  	if @user.save
      log_in @user
      redirect_to @user
      flash[:success] = "Welcome to the Sample App!"
  	else
  	   render 'new'	
  	 end  
  end
  private
  def user_params
      params.require(:user).permit(:name, :email,:phone, :password,
                                   :password_confirmation)
   end
   def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end

    # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
   

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
	   session[:user_id]=user.id
	end  
	def current_user
		@current_user ||=User.find_by(id: session[:user_id])
	end 
	def logged_in?
      !current_user.nil?
    end
    def log_out
    session.delete(:user_id)
    @current_user = nil
  end	
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/_footer.html.erb
<h1>footer</h1>

app/views/layouts/_header.html.erb
<div id="top">
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="container">
		<%= link_to "Get It Now",root_path,id: "logo" %>
		<ul class="nav navbar-nav navbar-right">
		   <% if logged_in? %>
		    <li><%= link_to "logout", logout_path, method: :delete %></li>
			<li><%= link_to "add post",new_product_path,method: :get %></li> 
			
			<% else %>
					   <li><%= link_to "Sign Up",'/signup' %></li>
		   <li><%= link_to "Log In",'/login' %></li> 
		    <% end %>
		</ul>
	</div>
</header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Deploy</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header' %>
  <div class="container">
       <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
    </div>

  </body>
</html>

app/views/products/_form.html.erb
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :des %>
    <%= f.text_field :des %>
  </div>

  <div class="field">
    <%= f.label :add %>
    <%= f.text_field :add %>
  </div>

  <div class="field">
    <%= f.label :time %>
    <%= f.text_field :time %>
  </div>



  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Des</th>
      <th>Add</th>
      <th>Time</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.des %></td>
        <td><%= product.add %></td>
        <td><%= product.time %></td>
        <td><%= product.user %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Des:</strong>
  <%= @product.des %>
</p>

<p>
  <strong>Add:</strong>
  <%= @product.add %>
</p>

<p>
  <strong>Time:</strong>
  <%= @product.time %>
</p>

<p>
  <strong>User:</strong>
  <%= @product.user %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<div class="row">
<div class="col-md-6 col-md-offset-3">
<%= form_for(@user) do |f| %>
 <%= render 'shared/error_messages' %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>
  
  
  <%= f.label :phone %>
  <%= f.text_field :phone %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "confirmation" %>
  <%= f.password_field :password_confirmation %>

 <div id="ent">
 </div>
  <%= f.submit "create account",class:"btn btn-primary"%>
 <% end %>
 </div>
 </div>

app/views/users/show.html.erb
<br>
<br>
<%= @user.name %>
<%= @user.email %>